services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vendor\Example\:
    resource: '../Classes/*'

  Vendor\Example\Data\HtmlProcessor:
    tags:
      -
        name: graphql.processor
        identifier: 'html'

  Vendor\Example\Data\ResultHandler:
    tags:
      -
        name: event.listener
        identifier: 'vendor-example-result'
        event: TYPO3\CMS\GraphQL\Event\AfterValueResolvingEvent